
/*
 * This file is generated by the parser generator.
 * Do not edit this file directly.
 * Instead, edit the grammar file and run the generator.
 */

import { randomBool, randomInt, randomChoice, randomChar, allChars } from "./generator-utils";
import { generateRandomCommentText, generateRandomDocComment, generateRandomString, generateName } from "./generate-text";

/* ==== Auxiliary types ==== */

export type Context = {
    maxWidth: number,
    maxDepth: number,
    elementWeight: { [key: string]: number },
    stopCodes: { [key: string]: string },
    depth: number,
}

export type Builder = string[]

export type Rule = (ctx: Context, b: Builder, field?: string) => void

/* ==== Auxiliary functions ==== */

export const createContext = (s: string, space: Rule) => ({
    s,
    p: 0,
    l: s.length,
    space,
});

export const getElementWeight = (ctx: Context, elementName: string) => {
    return ctx.elementWeight[elementName] || 1;
}

export const appendString = (ctx: Context, b: Builder, str: string) => {
    b.push(str);
}

export const appendClass = (ctx: Context, b: Builder, neg: boolean, chars: string[]) => {
    if (neg) {
        const allCharsArray = allChars.split("");
        chars = allCharsArray.filter(c => !chars.includes(c));
    }
    appendString(ctx, b, randomChoice(chars));
}

export const appendAny = (ctx: Context, b: Builder) => {
    appendString(ctx, b, randomChar(undefined));
}

export const singleLineComment = (ctx: Context, b: Builder) => {
    b.push("//");
    b.push(generateRandomCommentText(false));
    b.push("\n");
}

export const multiLineComment = (ctx: Context, b: Builder) => {
    b.push("/*");
    b.push(generateRandomCommentText(true));
    b.push("*/");
}

export const StringLiteral = (ctx: Context, b: Builder, str?: string) => {
    b.push("\"");
    b.push(generateRandomString());
    b.push("\"");
}

export const Id = (ctx: Context, b: Builder, str?: string) => {
    b.push(generateName(false));
}

export const TypeId = (ctx: Context, b: Builder, str?: string) => {
    b.push(generateName(true));
}

/* ==== Parser rules ==== */

export const Module: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Module"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  Module_star_0(ctx, b2, "imports");
  Module_star_1(ctx, b2, "items");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Import: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Import"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "import"))(ctx, b2);
  StringLiteral(ctx, b2, "path");
  appendString(ctx, b2, ";");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const moduleItem: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["moduleItem"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 8);
  if (choice === 0) {
    PrimitiveTypeDecl(ctx, b2);
  }
  if (choice === 1) {
    $Function(ctx, b2);
  }
  if (choice === 2) {
    AsmFunction(ctx, b2);
  }
  if (choice === 3) {
    NativeFunctionDecl(ctx, b2);
  }
  if (choice === 4) {
    Constant(ctx, b2);
  }
  if (choice === 5) {
    StructDecl(ctx, b2);
  }
  if (choice === 6) {
    MessageDecl(ctx, b2);
  }
  if (choice === 7) {
    Contract(ctx, b2);
  }
  if (choice === 8) {
    Trait(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const contractItemDecl: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["contractItemDecl"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 4);
  if (choice === 0) {
    ContractInit(ctx, b2);
  }
  if (choice === 1) {
    Receiver(ctx, b2);
  }
  if (choice === 2) {
    $Function(ctx, b2);
  }
  if (choice === 3) {
    Constant(ctx, b2);
  }
  if (choice === 4) {
    storageVar(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const traitItemDecl: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["traitItemDecl"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 3);
  if (choice === 0) {
    Receiver(ctx, b2);
  }
  if (choice === 1) {
    $Function(ctx, b2);
  }
  if (choice === 2) {
    Constant(ctx, b2);
  }
  if (choice === 3) {
    storageVar(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const PrimitiveTypeDecl: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["PrimitiveTypeDecl"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "primitive"))(ctx, b2);
  TypeId(ctx, b2, "name");
  appendString(ctx, b2, ";");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const $Function: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Function"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  $Function_star_2(ctx, b2, "attributes");
  keyword((ctx, b) => appendString(ctx, b, "fun"))(ctx, b2);
  Id(ctx, b2, "name");
  ParameterList(Parameter)(ctx, b2, "parameters");
  $Function_optional_3(ctx, b2, "returnType");
  $Function_alt_4(ctx, b2, "body");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const FunctionDefinition: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["FunctionDefinition"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  statements(ctx, b2, "body");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const FunctionDeclaration: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["FunctionDeclaration"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  semicolon(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const AsmFunction: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["AsmFunction"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "asm");
  AsmFunction_optional_5(ctx, b2, "shuffle");
  AsmFunction_star_6(ctx, b2, "attributes");
  keyword((ctx, b) => appendString(ctx, b, "fun"))(ctx, b2);
  Id(ctx, b2, "name");
  ParameterList(Parameter)(ctx, b2, "parameters");
  AsmFunction_optional_7(ctx, b2, "returnType");
  appendString(ctx, b2, "{");
  assembly(ctx, b2, "instructions");
  appendString(ctx, b2, "}");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const shuffle: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["shuffle"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "(");
  shuffle_star_8(ctx, b2, "ids");
  shuffle_optional_11(ctx, b2, "to");
  appendString(ctx, b2, ")");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const NativeFunctionDecl: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["NativeFunctionDecl"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "@name");
  appendString(ctx, b2, "(");
  NativeFunctionDecl_lex_12(ctx, b2, "nativeName");
  appendString(ctx, b2, ")");
  NativeFunctionDecl_star_13(ctx, b2, "attributes");
  keyword((ctx, b) => appendString(ctx, b, "native"))(ctx, b2);
  Id(ctx, b2, "name");
  ParameterList(Parameter)(ctx, b2, "parameters");
  NativeFunctionDecl_optional_14(ctx, b2, "returnType");
  appendString(ctx, b2, ";");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Constant: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Constant"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  Constant_star_15(ctx, b2, "attributes");
  keyword((ctx, b) => appendString(ctx, b, "const"))(ctx, b2);
  Id(ctx, b2, "name");
  ascription(ctx, b2, "type");
  Constant_alt_16(ctx, b2, "body");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const ConstantAttribute: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["ConstantAttribute"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  ConstantAttribute_alt_17(ctx, b2, "name");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const ConstantDefinition: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["ConstantDefinition"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "=");
  expression(ctx, b2, "expression");
  semicolon(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const ConstantDeclaration: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["ConstantDeclaration"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  semicolon(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const storageVar: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["storageVar"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  FieldDecl(ctx, b2);
  semicolon(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StructDecl: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StructDecl"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "struct");
  TypeId(ctx, b2, "name");
  appendString(ctx, b2, "{");
  structFields(ctx, b2, "fields");
  appendString(ctx, b2, "}");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const MessageDecl: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["MessageDecl"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "message");
  MessageDecl_optional_19(ctx, b2, "opcode");
  TypeId(ctx, b2, "name");
  appendString(ctx, b2, "{");
  structFields(ctx, b2, "fields");
  appendString(ctx, b2, "}");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const structFields: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["structFields"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  structFields_optional_20(ctx, b2);
  structFields_optional_21(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const FieldDecl: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["FieldDecl"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  Id(ctx, b2, "name");
  ascription(ctx, b2, "type");
  FieldDecl_optional_23(ctx, b2, "expression");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Contract: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Contract"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  Contract_star_24(ctx, b2, "attributes");
  keyword((ctx, b) => appendString(ctx, b, "contract"))(ctx, b2);
  Id(ctx, b2, "name");
  Contract_optional_25(ctx, b2, "parameters");
  Contract_optional_26(ctx, b2, "traits");
  appendString(ctx, b2, "{");
  Contract_star_27(ctx, b2, "declarations");
  appendString(ctx, b2, "}");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Trait: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Trait"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  Trait_star_28(ctx, b2, "attributes");
  keyword((ctx, b) => appendString(ctx, b, "trait"))(ctx, b2);
  Id(ctx, b2, "name");
  Trait_optional_29(ctx, b2, "traits");
  appendString(ctx, b2, "{");
  Trait_star_30(ctx, b2, "declarations");
  appendString(ctx, b2, "}");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const inheritedTraits: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["inheritedTraits"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "with"))(ctx, b2);
  commaList(Id)(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const ContractInit: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["ContractInit"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "init");
  ParameterList(Parameter)(ctx, b2, "parameters");
  statements(ctx, b2, "body");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const ContractAttribute: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["ContractAttribute"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "@interface");
  appendString(ctx, b2, "(");
  StringLiteral(ctx, b2, "name");
  appendString(ctx, b2, ")");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const FunctionAttribute: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["FunctionAttribute"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  FunctionAttribute_alt_31(ctx, b2, "name");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const GetAttribute: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["GetAttribute"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "get");
  GetAttribute_optional_33(ctx, b2, "methodId");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Receiver: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Receiver"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  ReceiverType(ctx, b2, "type");
  appendString(ctx, b2, "(");
  receiverParam(ctx, b2, "param");
  appendString(ctx, b2, ")");
  statements(ctx, b2, "body");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const ReceiverType: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["ReceiverType"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  ReceiverType_alt_34(ctx, b2, "name");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const receiverParam: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["receiverParam"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  receiverParam_optional_36(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const assembly: Rule = (ctx, b, field) => {
  assembly_stringify_37(ctx, b);
};
export const assemblySequence: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    assemblyItem(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const assemblyItem: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["assemblyItem"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 3);
  if (choice === 0) {
    assemblyItem_seq_38(ctx, b2);
  }
  if (choice === 1) {
    Comment(ctx, b2);
  }
  if (choice === 2) {
    assemblyItem_seq_40(ctx, b2);
  }
  if (choice === 3) {
    assemblyItem_plus_44(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const ascription: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["ascription"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, ":");
  $type(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const $type: Rule = (ctx, b, field) => {
  return TypeAs(ctx, b, field);
};
export const TypeAs: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["TypeAs"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  TypeOptional(ctx, b2, "type");
  TypeAs_star_46(ctx, b2, "as");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const TypeOptional: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["TypeOptional"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  typePrimary(ctx, b2, "type");
  TypeOptional_star_47(ctx, b2, "optionals");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const typePrimary: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["typePrimary"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    TypeGeneric(ctx, b2);
  }
  if (choice === 1) {
    TypeRegular(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const TypeRegular: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["TypeRegular"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  TypeId(ctx, b2, "child");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const TypeGeneric: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["TypeGeneric"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  TypeGeneric_alt_48(ctx, b2, "name");
  appendString(ctx, b2, "<");
  commaList($type)(ctx, b2, "args");
  appendString(ctx, b2, ">");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const MapKeyword: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["MapKeyword"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "map"))(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Bounced: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Bounced"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "bounced");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
;
export const statement: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["statement"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 11);
  if (choice === 0) {
    StatementLet(ctx, b2);
  }
  if (choice === 1) {
    StatementDestruct(ctx, b2);
  }
  if (choice === 2) {
    StatementBlock(ctx, b2);
  }
  if (choice === 3) {
    StatementReturn(ctx, b2);
  }
  if (choice === 4) {
    StatementCondition(ctx, b2);
  }
  if (choice === 5) {
    StatementWhile(ctx, b2);
  }
  if (choice === 6) {
    StatementRepeat(ctx, b2);
  }
  if (choice === 7) {
    StatementUntil(ctx, b2);
  }
  if (choice === 8) {
    StatementTry(ctx, b2);
  }
  if (choice === 9) {
    StatementForEach(ctx, b2);
  }
  if (choice === 10) {
    StatementExpression(ctx, b2);
  }
  if (choice === 11) {
    StatementAssign(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const statements: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["statements"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "{");
  statements_star_53(ctx, b2);
  appendString(ctx, b2, "}");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementLet: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementLet"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "let"))(ctx, b2);
  Id(ctx, b2, "name");
  StatementLet_optional_54(ctx, b2, "type");
  appendString(ctx, b2, "=");
  expression(ctx, b2, "init");
  semicolon(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementDestruct: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementDestruct"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "let"))(ctx, b2);
  TypeId(ctx, b2, "type");
  appendString(ctx, b2, "{");
  inter(destructItem, (ctx, b) => appendString(ctx, b, ","))(ctx, b2, "fields");
  optionalRest(ctx, b2, "rest");
  appendString(ctx, b2, "}");
  appendString(ctx, b2, "=");
  expression(ctx, b2, "init");
  semicolon(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementBlock: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementBlock"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  statements(ctx, b2, "body");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementReturn: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementReturn"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "return"))(ctx, b2);
  StatementReturn_optional_55(ctx, b2, "expression");
  semicolon(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementExpression: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementExpression"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  expression(ctx, b2, "expression");
  semicolon(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementAssign: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementAssign"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  expression(ctx, b2, "left");
  StatementAssign_optional_56(ctx, b2, "operator");
  appendString(ctx, b2, "=");
  expression(ctx, b2, "right");
  semicolon(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementCondition: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementCondition"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "if"))(ctx, b2);
  expression(ctx, b2, "condition");
  statements(ctx, b2, "trueBranch");
  StatementCondition_optional_59(ctx, b2, "falseBranch");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementWhile: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementWhile"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "while"))(ctx, b2);
  parens(ctx, b2, "condition");
  statements(ctx, b2, "body");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementRepeat: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementRepeat"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "repeat"))(ctx, b2);
  parens(ctx, b2, "condition");
  statements(ctx, b2, "body");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementUntil: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementUntil"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "do"))(ctx, b2);
  statements(ctx, b2, "body");
  keyword((ctx, b) => appendString(ctx, b, "until"))(ctx, b2);
  parens(ctx, b2, "condition");
  semicolon(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementTry: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementTry"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "try"))(ctx, b2);
  statements(ctx, b2, "body");
  StatementTry_optional_61(ctx, b2, "handler");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementForEach: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StatementForEach"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "foreach"))(ctx, b2);
  appendString(ctx, b2, "(");
  Id(ctx, b2, "key");
  appendString(ctx, b2, ",");
  Id(ctx, b2, "value");
  appendString(ctx, b2, "in");
  expression(ctx, b2, "expression");
  appendString(ctx, b2, ")");
  statements(ctx, b2, "body");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const augmentedOp: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["augmentedOp"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 4);
  if (choice === 0) {
    appendString(ctx, b2, "||");
  }
  if (choice === 1) {
    appendString(ctx, b2, "&&");
  }
  if (choice === 2) {
    appendString(ctx, b2, ">>");
  }
  if (choice === 3) {
    appendString(ctx, b2, "<<");
  }
  if (choice === 4) {
    appendClass(ctx, b2, false, ["-", "+", "*", "/", "%", "|", "&", "^"]);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const FalseBranch: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["FalseBranch"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  statements(ctx, b2, "body");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const semicolon: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["semicolon"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    appendString(ctx, b2, ";");
  }
  if (choice === 1) {
    semicolon_lookpos_62(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const destructItem: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["destructItem"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    RegularField(ctx, b2);
  }
  if (choice === 1) {
    PunnedField(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const RegularField: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["RegularField"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  Id(ctx, b2, "fieldName");
  appendString(ctx, b2, ":");
  Id(ctx, b2, "varName");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const PunnedField: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["PunnedField"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  Id(ctx, b2, "name");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const optionalRest: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["optionalRest"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    optionalRest_seq_63(ctx, b2);
  }
  if (choice === 1) {
    NoRestArgument(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const RestArgument: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["RestArgument"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "..");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const NoRestArgument: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    appendString(ctx, b2, ",");
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const expression: Rule = (ctx, b, field) => {
  return Conditional(ctx, b, field);
};
export const Conditional: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Conditional"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  or(ctx, b2, "head");
  Conditional_optional_65(ctx, b2, "tail");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const or: Rule = (ctx, b, field) => {
  return Binary(and, (ctx, b) => appendString(ctx, b, "||"))(ctx, b, field);
};
export const and: Rule = (ctx, b, field) => {
  return Binary(bitwiseOr, (ctx, b) => appendString(ctx, b, "&&"))(ctx, b, field);
};
export const bitwiseOr: Rule = (ctx, b, field) => {
  return Binary(bitwiseXor, (ctx, b) => appendString(ctx, b, "|"))(ctx, b, field);
};
export const bitwiseXor: Rule = (ctx, b, field) => {
  return Binary(bitwiseAnd, (ctx, b) => appendString(ctx, b, "^"))(ctx, b, field);
};
export const bitwiseAnd: Rule = (ctx, b, field) => {
  return Binary(equality, (ctx, b) => appendString(ctx, b, "&"))(ctx, b, field);
};
export const equality: Rule = (ctx, b, field) => {
  return Binary(compare, equality_alt_66)(ctx, b, field);
};
export const compare: Rule = (ctx, b, field) => {
  return Binary(bitwiseShift, compare_alt_67)(ctx, b, field);
};
export const bitwiseShift: Rule = (ctx, b, field) => {
  return Binary(add, bitwiseShift_alt_68)(ctx, b, field);
};
export const add: Rule = (ctx, b, field) => {
  return Binary(mul, add_alt_69)(ctx, b, field);
};
export const mul: Rule = (ctx, b, field) => {
  return Binary(Unary, (ctx, b) => appendClass(ctx, b, false, ["*", "/", "%"]))(ctx, b, field);
};
export const Unary: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Unary"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  Unary_star_70(ctx, b2, "prefixes");
  Suffix(ctx, b2, "expression");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Suffix: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Suffix"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  primary(ctx, b2, "expression");
  Suffix_star_71(ctx, b2, "suffixes");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Binary: (T: Rule, U: Rule) => Rule = (T, U) => {
  return (ctx, b, field) => {
    if (ctx.depth > ctx.maxDepth) {
      b.push(ctx.stopCodes["Binary"] || "");
      return;
    }
    ctx.depth++;
    const b2: Builder = [];
    inter(T, Operator(U))(ctx, b2, "exprs");
    if (b2.length > 0) {
      b.push(...b2);
    }
    ctx.depth--;
  };
};
export const Operator: (U: Rule) => Rule = U => {
  return (ctx, b, field) => {
    if (ctx.depth > ctx.maxDepth) {
      b.push(ctx.stopCodes["Operator"] || "");
      return;
    }
    ctx.depth++;
    const b2: Builder = [];
    U(ctx, b2, "name");
    if (b2.length > 0) {
      b.push(...b2);
    }
    ctx.depth--;
  };
};
export const suffix: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["suffix"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 2);
  if (choice === 0) {
    SuffixUnboxNotNull(ctx, b2);
  }
  if (choice === 1) {
    SuffixCall(ctx, b2);
  }
  if (choice === 2) {
    SuffixFieldAccess(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const SuffixUnboxNotNull: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["SuffixUnboxNotNull"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "!!");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const SuffixCall: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["SuffixCall"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  ParameterList(expression)(ctx, b2, "params");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const SuffixFieldAccess: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["SuffixFieldAccess"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, ".");
  Id(ctx, b2, "name");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const primary: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["primary"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 8);
  if (choice === 0) {
    Parens(ctx, b2);
  }
  if (choice === 1) {
    StructInstance(ctx, b2);
  }
  if (choice === 2) {
    IntegerLiteral(ctx, b2);
  }
  if (choice === 3) {
    BoolLiteral(ctx, b2);
  }
  if (choice === 4) {
    InitOf(ctx, b2);
  }
  if (choice === 5) {
    CodeOf(ctx, b2);
  }
  if (choice === 6) {
    Null(ctx, b2);
  }
  if (choice === 7) {
    StringLiteral(ctx, b2);
  }
  if (choice === 8) {
    Id(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const Null: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Null"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "null"))(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const parens: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["parens"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "(");
  expression(ctx, b2);
  appendString(ctx, b2, ")");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Parens: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Parens"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  parens(ctx, b2, "child");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StructInstance: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StructInstance"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  TypeId(ctx, b2, "type");
  StructInstanceFields(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StructInstanceFields: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StructInstanceFields"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "{");
  StructInstanceFields_optional_72(ctx, b2, "fields");
  appendString(ctx, b2, "}");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const InitOf: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["InitOf"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "initOf"))(ctx, b2);
  Id(ctx, b2, "name");
  ParameterList(expression)(ctx, b2, "params");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const CodeOf: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["CodeOf"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "codeOf");
  Id(ctx, b2, "name");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StructFieldInitializer: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["StructFieldInitializer"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  Id(ctx, b2, "name");
  StructFieldInitializer_optional_74(ctx, b2, "init");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const ParameterList: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {
    if (ctx.depth > ctx.maxDepth) {
      b.push(ctx.stopCodes["ParameterList"] || "");
      return;
    }
    ctx.depth++;
    const b2: Builder = [];
    appendString(ctx, b2, "(");
    ParameterList_optional_75(T)(ctx, b2);
    appendString(ctx, b2, ")");
    if (b2.length > 0) {
      b.push(...b2);
    }
    ctx.depth--;
  };
};
export const Parameter: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Parameter"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  Id(ctx, b2, "name");
  ascription(ctx, b2, "type");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const commaList: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {
    if (ctx.depth > ctx.maxDepth) {
      b.push(ctx.stopCodes["commaList"] || "");
      return;
    }
    ctx.depth++;
    const b2: Builder = [];
    inter(T, (ctx, b) => appendString(ctx, b, ","))(ctx, b2);
    commaList_optional_76(T)(ctx, b2);
    if (b2.length > 0) {
      b.push(...b2);
    }
    ctx.depth--;
  };
};
export const IntegerLiteral: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["IntegerLiteral"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  IntegerLiteral_alt_77(ctx, b2, "value");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const IntegerLiteralDec: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["IntegerLiteralDec"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  IntegerLiteralDec_lex_78(ctx, b2, "digits");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const IntegerLiteralHex: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["IntegerLiteralHex"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  IntegerLiteralHex_lex_80(ctx, b2, "digits");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const IntegerLiteralBin: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["IntegerLiteralBin"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  IntegerLiteralBin_lex_82(ctx, b2, "digits");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const IntegerLiteralOct: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["IntegerLiteralOct"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  IntegerLiteralOct_lex_84(ctx, b2, "digits");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const underscored: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {
    underscored_seq_88(T)(ctx, b);
  };
};
export const digit: Rule = (ctx, b, field) => {
  return appendClass(ctx, b, false, ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]);
};
export const idPart: Rule = (ctx, b, field) => {
  return appendClass(ctx, b, false, ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "_"]);
};
;
export const FuncId: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["FuncId"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  FuncId_optional_94(ctx, b2, "accessor");
  FuncId_stringify_99(ctx, b2, "id");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const BoolLiteral: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["BoolLiteral"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  BoolLiteral_alt_100(ctx, b2, "value");
  BoolLiteral_lookneg_101(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
;
export const escapeChar: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["escapeChar"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 3);
  if (choice === 0) {
    appendClass(ctx, b2, false, ["\\", "\"", "n", "r", "t", "v", "b", "f"]);
  }
  if (choice === 1) {
    escapeChar_seq_115(ctx, b2);
  }
  if (choice === 2) {
    escapeChar_seq_118(ctx, b2);
  }
  if (choice === 3) {
    escapeChar_seq_121(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const hexDigit: Rule = (ctx, b, field) => {
  return appendClass(ctx, b, false, ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "A", "B", "C", "D", "E", "F"]);
};
export const keyword: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {
    keyword_seq_123(T)(ctx, b);
  };
};
export const reservedWord: Rule = (ctx, b, field) => {
  return keyword(reservedWord_alt_124)(ctx, b, field);
};
export const space: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth - 1);
  space_alt_128(ctx, b2);
  for (let i = 0; i < count; i++) {
    space_alt_128(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const Comment: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["Comment"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    multiLineComment(ctx, b2);
  }
  if (choice === 1) {
    singleLineComment(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
;
;
export const JustImports: Rule = (ctx, b, field) => {
  if (ctx.depth > ctx.maxDepth) {
    b.push(ctx.stopCodes["JustImports"] || "");
    return;
  }
  ctx.depth++;
  const b2: Builder = [];
  JustImports_star_135(ctx, b2, "imports");
  JustImports_star_136(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const inter: (A: Rule, B: Rule) => Rule = (A, B) => {
  return (ctx, b, field) => {
    if (ctx.depth > ctx.maxDepth) {
      b.push(ctx.stopCodes["inter"] || "");
      return;
    }
    ctx.depth++;
    const b2: Builder = [];
    A(ctx, b2, "head");
    inter_star_138(A, B)(ctx, b2, "tail");
    if (b2.length > 0) {
      b.push(...b2);
    }
    ctx.depth--;
  };
};
export const Module_star_0: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    Import(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const Module_star_1: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    moduleItem(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const $Function_star_2: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    FunctionAttribute(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const $Function_optional_3: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    ascription(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const $Function_alt_4: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    FunctionDefinition(ctx, b2);
  }
  if (choice === 1) {
    FunctionDeclaration(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const AsmFunction_optional_5: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    shuffle(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const AsmFunction_star_6: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    FunctionAttribute(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const AsmFunction_optional_7: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    ascription(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const shuffle_star_8: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    Id(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const shuffle_plus_9: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth - 1);
  IntegerLiteralDec(ctx, b2);
  for (let i = 0; i < count; i++) {
    IntegerLiteralDec(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const shuffle_seq_10: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "->");
  shuffle_plus_9(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const shuffle_optional_11: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    shuffle_seq_10(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const NativeFunctionDecl_lex_12: Rule = (ctx, b, field) => {
  FuncId(ctx, b);
};
export const NativeFunctionDecl_star_13: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    FunctionAttribute(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const NativeFunctionDecl_optional_14: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    ascription(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const Constant_star_15: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    ConstantAttribute(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const Constant_alt_16: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    ConstantDefinition(ctx, b2);
  }
  if (choice === 1) {
    ConstantDeclaration(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const ConstantAttribute_alt_17: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 2);
  if (choice === 0) {
    keyword((ctx, b) => appendString(ctx, b, "virtual"))(ctx, b2);
  }
  if (choice === 1) {
    keyword((ctx, b) => appendString(ctx, b, "override"))(ctx, b2);
  }
  if (choice === 2) {
    keyword((ctx, b) => appendString(ctx, b, "abstract"))(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const MessageDecl_seq_18: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "(");
  expression(ctx, b2);
  appendString(ctx, b2, ")");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const MessageDecl_optional_19: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    MessageDecl_seq_18(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const structFields_optional_20: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    inter(FieldDecl, (ctx, b) => appendString(ctx, b, ";"))(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const structFields_optional_21: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    appendString(ctx, b2, ";");
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const FieldDecl_seq_22: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "=");
  expression(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const FieldDecl_optional_23: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    FieldDecl_seq_22(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const Contract_star_24: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    ContractAttribute(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const Contract_optional_25: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    ParameterList(Parameter)(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const Contract_optional_26: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    inheritedTraits(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const Contract_star_27: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    contractItemDecl(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const Trait_star_28: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    ContractAttribute(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const Trait_optional_29: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    inheritedTraits(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const Trait_star_30: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    traitItemDecl(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const FunctionAttribute_alt_31: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 6);
  if (choice === 0) {
    GetAttribute(ctx, b2);
  }
  if (choice === 1) {
    keyword((ctx, b) => appendString(ctx, b, "mutates"))(ctx, b2);
  }
  if (choice === 2) {
    keyword((ctx, b) => appendString(ctx, b, "extends"))(ctx, b2);
  }
  if (choice === 3) {
    keyword((ctx, b) => appendString(ctx, b, "virtual"))(ctx, b2);
  }
  if (choice === 4) {
    keyword((ctx, b) => appendString(ctx, b, "override"))(ctx, b2);
  }
  if (choice === 5) {
    keyword((ctx, b) => appendString(ctx, b, "inline"))(ctx, b2);
  }
  if (choice === 6) {
    keyword((ctx, b) => appendString(ctx, b, "abstract"))(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const GetAttribute_seq_32: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "(");
  expression(ctx, b2);
  appendString(ctx, b2, ")");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const GetAttribute_optional_33: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    GetAttribute_seq_32(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const ReceiverType_alt_34: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 2);
  if (choice === 0) {
    appendString(ctx, b2, "bounced");
  }
  if (choice === 1) {
    keyword((ctx, b) => appendString(ctx, b, "receive"))(ctx, b2);
  }
  if (choice === 2) {
    keyword((ctx, b) => appendString(ctx, b, "external"))(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const receiverParam_alt_35: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    Parameter(ctx, b2);
  }
  if (choice === 1) {
    StringLiteral(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const receiverParam_optional_36: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    receiverParam_alt_35(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const assembly_stringify_37: Rule = (ctx, b, field) => {
  assemblySequence(ctx, b);
};
export const assemblyItem_seq_38: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "{");
  assemblySequence(ctx, b2);
  appendString(ctx, b2, "}");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const assemblyItem_star_39: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    appendClass(ctx, b2, true, ["\""]);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const assemblyItem_seq_40: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "\"");
  assemblyItem_star_39(ctx, b2);
  appendString(ctx, b2, "\"");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const assemblyItem_alt_41: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 2);
  if (choice === 0) {
    appendClass(ctx, b2, false, ["\"", "{", "}"]);
  }
  if (choice === 1) {
    appendString(ctx, b2, "//");
  }
  if (choice === 2) {
    appendString(ctx, b2, "/*");
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const assemblyItem_lookneg_42: Rule = (ctx, b, field) => {};
export const assemblyItem_seq_43: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  assemblyItem_lookneg_42(ctx, b2);
  appendAny(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const assemblyItem_plus_44: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth - 1);
  assemblyItem_seq_43(ctx, b2);
  for (let i = 0; i < count; i++) {
    assemblyItem_seq_43(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const TypeAs_seq_45: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "as"))(ctx, b2);
  Id(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const TypeAs_star_46: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    TypeAs_seq_45(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const TypeOptional_star_47: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    appendString(ctx, b2, "?");
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const TypeGeneric_alt_48: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 2);
  if (choice === 0) {
    MapKeyword(ctx, b2);
  }
  if (choice === 1) {
    Bounced(ctx, b2);
  }
  if (choice === 2) {
    TypeId(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const TypeId_star_49: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    appendClass(ctx, b2, false, ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "_"]);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const TypeId_seq_50: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendClass(ctx, b2, false, ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]);
  TypeId_star_49(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const TypeId_stringify_51: Rule = (ctx, b, field) => {
  TypeId_seq_50(ctx, b);
};
export const TypeId_lex_52: Rule = (ctx, b, field) => {
  TypeId_stringify_51(ctx, b);
};
export const statements_star_53: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    statement(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const StatementLet_optional_54: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    ascription(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const StatementReturn_optional_55: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    expression(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const StatementAssign_optional_56: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    augmentedOp(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const StatementCondition_alt_57: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    FalseBranch(ctx, b2);
  }
  if (choice === 1) {
    StatementCondition(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const StatementCondition_seq_58: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "else"))(ctx, b2);
  StatementCondition_alt_57(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementCondition_optional_59: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    StatementCondition_seq_58(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const StatementTry_seq_60: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  keyword((ctx, b) => appendString(ctx, b, "catch"))(ctx, b2);
  appendString(ctx, b2, "(");
  Id(ctx, b2, "name");
  appendString(ctx, b2, ")");
  statements(ctx, b2, "body");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StatementTry_optional_61: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    StatementTry_seq_60(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const semicolon_lookpos_62: Rule = (ctx, b, field) => {};
export const optionalRest_seq_63: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, ",");
  RestArgument(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Conditional_seq_64: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "?");
  or(ctx, b2, "thenBranch");
  appendString(ctx, b2, ":");
  Conditional(ctx, b2, "elseBranch");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Conditional_optional_65: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    Conditional_seq_64(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const equality_alt_66: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    appendString(ctx, b2, "!=");
  }
  if (choice === 1) {
    appendString(ctx, b2, "==");
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const compare_alt_67: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 3);
  if (choice === 0) {
    appendString(ctx, b2, "<=");
  }
  if (choice === 1) {
    appendString(ctx, b2, "<");
  }
  if (choice === 2) {
    appendString(ctx, b2, ">=");
  }
  if (choice === 3) {
    appendString(ctx, b2, ">");
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const bitwiseShift_alt_68: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    appendString(ctx, b2, "<<");
  }
  if (choice === 1) {
    appendString(ctx, b2, ">>");
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const add_alt_69: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    appendString(ctx, b2, "+");
  }
  if (choice === 1) {
    appendString(ctx, b2, "-");
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const Unary_star_70: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    Operator((ctx, b) => appendClass(ctx, b, false, ["-", "+", "!", "~"]))(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const Suffix_star_71: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    suffix(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const StructInstanceFields_optional_72: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    commaList(StructFieldInitializer)(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const StructFieldInitializer_seq_73: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, ":");
  expression(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StructFieldInitializer_optional_74: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    StructFieldInitializer_seq_73(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const ParameterList_optional_75: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {
    const b2: Builder = [];
    const shouldUseB = randomBool();
    if (shouldUseB) {
      commaList(T)(ctx, b2);
    }
    if (b2.length > 0) {
      b.push(...b2);
    }
  };
};
export const commaList_optional_76: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {
    const b2: Builder = [];
    const shouldUseB = randomBool();
    if (shouldUseB) {
      appendString(ctx, b2, ",");
    }
    if (b2.length > 0) {
      b.push(...b2);
    }
  };
};
export const IntegerLiteral_alt_77: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 3);
  if (choice === 0) {
    IntegerLiteralHex(ctx, b2);
  }
  if (choice === 1) {
    IntegerLiteralBin(ctx, b2);
  }
  if (choice === 2) {
    IntegerLiteralOct(ctx, b2);
  }
  if (choice === 3) {
    IntegerLiteralDec(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const IntegerLiteralDec_lex_78: Rule = (ctx, b, field) => {
  underscored(digit)(ctx, b);
};
export const IntegerLiteralHex_seq_79: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "0");
  appendClass(ctx, b2, false, ["x", "X"]);
  underscored(hexDigit)(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const IntegerLiteralHex_lex_80: Rule = (ctx, b, field) => {
  IntegerLiteralHex_seq_79(ctx, b);
};
export const IntegerLiteralBin_seq_81: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "0");
  appendClass(ctx, b2, false, ["b", "B"]);
  underscored((ctx, b) => appendClass(ctx, b, false, ["0", "1"]))(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const IntegerLiteralBin_lex_82: Rule = (ctx, b, field) => {
  IntegerLiteralBin_seq_81(ctx, b);
};
export const IntegerLiteralOct_seq_83: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "0");
  appendClass(ctx, b2, false, ["o", "O"]);
  underscored((ctx, b) => appendClass(ctx, b, false, ["0", "1", "2", "3", "4", "5", "6", "7"]))(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const IntegerLiteralOct_lex_84: Rule = (ctx, b, field) => {
  IntegerLiteralOct_seq_83(ctx, b);
};
export const underscored_optional_85: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {
    const b2: Builder = [];
    const shouldUseB = randomBool();
    if (shouldUseB) {
      appendString(ctx, b2, "_");
    }
    if (b2.length > 0) {
      b.push(...b2);
    }
  };
};
export const underscored_seq_86: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {
    ctx.depth++;
    const b2: Builder = [];
    underscored_optional_85(T)(ctx, b2);
    T(ctx, b2);
    if (b2.length > 0) {
      b.push(...b2);
    }
    ctx.depth--;
  };
};
export const underscored_star_87: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {
    const b2: Builder = [];
    const maxWidth = ctx.maxWidth,
      count = randomInt(0, maxWidth);
    for (let i = 0; i < count; i++) {
      underscored_seq_86(T)(ctx, b2);
    }
    if (b2.length > 0) {
      b.push(...b2);
    }
    return true;
  };
};
export const underscored_seq_88: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {
    ctx.depth++;
    const b2: Builder = [];
    T(ctx, b2);
    underscored_star_87(T)(ctx, b2);
    if (b2.length > 0) {
      b.push(...b2);
    }
    ctx.depth--;
  };
};
export const Id_lookneg_89: Rule = (ctx, b, field) => {};
export const Id_star_90: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    idPart(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const Id_seq_91: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  Id_lookneg_89(ctx, b2);
  appendClass(ctx, b2, false, ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "_"]);
  Id_star_90(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const Id_stringify_92: Rule = (ctx, b, field) => {
  Id_seq_91(ctx, b);
};
export const Id_lex_93: Rule = (ctx, b, field) => {
  Id_stringify_92(ctx, b);
};
export const FuncId_optional_94: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    appendClass(ctx, b2, false, [".", "~"]);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const FuncId_plus_95: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth - 1);
  appendClass(ctx, b2, true, ["`", "\n", "\r", "\t", "\b", "\n", "\r", "\t", "\b"]);
  for (let i = 0; i < count; i++) {
    appendClass(ctx, b2, true, ["`", "\n", "\r", "\t", "\b", "\n", "\r", "\t", "\b"]);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const FuncId_seq_96: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "`");
  FuncId_plus_95(ctx, b2);
  appendString(ctx, b2, "`");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const FuncId_plus_97: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth - 1);
  appendClass(ctx, b2, true, [" ", "\n", "\r", "\t", "\b", "\n", "\r", "\t", "\b", "\n", "\r", "\t", "\b", "(", ")", "[", "\"\\]\"", ",", ".", ";", "~"]);
  for (let i = 0; i < count; i++) {
    appendClass(ctx, b2, true, [" ", "\n", "\r", "\t", "\b", "\n", "\r", "\t", "\b", "\n", "\r", "\t", "\b", "(", ")", "[", "\"\\]\"", ",", ".", ";", "~"]);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const FuncId_alt_98: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    FuncId_seq_96(ctx, b2);
  }
  if (choice === 1) {
    FuncId_plus_97(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const FuncId_stringify_99: Rule = (ctx, b, field) => {
  FuncId_alt_98(ctx, b);
};
export const BoolLiteral_alt_100: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    appendString(ctx, b2, "true");
  }
  if (choice === 1) {
    appendString(ctx, b2, "false");
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const BoolLiteral_lookneg_101: Rule = (ctx, b, field) => {};
export const StringLiteral_seq_102: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "\\");
  escapeChar(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StringLiteral_alt_103: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    appendClass(ctx, b2, true, ["\"", "\\"]);
  }
  if (choice === 1) {
    StringLiteral_seq_102(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const StringLiteral_star_104: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    StringLiteral_alt_103(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const StringLiteral_stringify_105: Rule = (ctx, b, field) => {
  StringLiteral_star_104(ctx, b);
};
export const StringLiteral_seq_106: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "\"");
  StringLiteral_stringify_105(ctx, b2);
  appendString(ctx, b2, "\"");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const StringLiteral_lex_107: Rule = (ctx, b, field) => {
  StringLiteral_seq_106(ctx, b);
};
export const escapeChar_optional_108: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    hexDigit(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const escapeChar_optional_109: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    hexDigit(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const escapeChar_optional_110: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    hexDigit(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const escapeChar_optional_111: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    hexDigit(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const escapeChar_optional_112: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const shouldUseB = randomBool();
  if (shouldUseB) {
    hexDigit(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const escapeChar_seq_113: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  hexDigit(ctx, b2);
  escapeChar_optional_108(ctx, b2);
  escapeChar_optional_109(ctx, b2);
  escapeChar_optional_110(ctx, b2);
  escapeChar_optional_111(ctx, b2);
  escapeChar_optional_112(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const escapeChar_stringify_114: Rule = (ctx, b, field) => {
  escapeChar_seq_113(ctx, b);
};
export const escapeChar_seq_115: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "u{");
  escapeChar_stringify_114(ctx, b2);
  appendString(ctx, b2, "}");
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const escapeChar_seq_116: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  hexDigit(ctx, b2);
  hexDigit(ctx, b2);
  hexDigit(ctx, b2);
  hexDigit(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const escapeChar_stringify_117: Rule = (ctx, b, field) => {
  escapeChar_seq_116(ctx, b);
};
export const escapeChar_seq_118: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "u");
  escapeChar_stringify_117(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const escapeChar_seq_119: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  hexDigit(ctx, b2);
  hexDigit(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const escapeChar_stringify_120: Rule = (ctx, b, field) => {
  escapeChar_seq_119(ctx, b);
};
export const escapeChar_seq_121: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  appendString(ctx, b2, "x");
  escapeChar_stringify_120(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const keyword_lookneg_122: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {};
};
export const keyword_seq_123: (T: Rule) => Rule = T => {
  return (ctx, b, field) => {
    ctx.depth++;
    const b2: Builder = [];
    T(ctx, b2);
    keyword_lookneg_122(T)(ctx, b2);
    if (b2.length > 0) {
      b.push(...b2);
    }
    ctx.depth--;
  };
};
export const reservedWord_alt_124: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 31);
  if (choice === 0) {
    appendString(ctx, b2, "extend");
  }
  if (choice === 1) {
    appendString(ctx, b2, "public");
  }
  if (choice === 2) {
    appendString(ctx, b2, "fun");
  }
  if (choice === 3) {
    appendString(ctx, b2, "let");
  }
  if (choice === 4) {
    appendString(ctx, b2, "return");
  }
  if (choice === 5) {
    appendString(ctx, b2, "receive");
  }
  if (choice === 6) {
    appendString(ctx, b2, "native");
  }
  if (choice === 7) {
    appendString(ctx, b2, "primitive");
  }
  if (choice === 8) {
    appendString(ctx, b2, "null");
  }
  if (choice === 9) {
    appendString(ctx, b2, "if");
  }
  if (choice === 10) {
    appendString(ctx, b2, "else");
  }
  if (choice === 11) {
    appendString(ctx, b2, "while");
  }
  if (choice === 12) {
    appendString(ctx, b2, "repeat");
  }
  if (choice === 13) {
    appendString(ctx, b2, "do");
  }
  if (choice === 14) {
    appendString(ctx, b2, "until");
  }
  if (choice === 15) {
    appendString(ctx, b2, "try");
  }
  if (choice === 16) {
    appendString(ctx, b2, "catch");
  }
  if (choice === 17) {
    appendString(ctx, b2, "foreach");
  }
  if (choice === 18) {
    appendString(ctx, b2, "as");
  }
  if (choice === 19) {
    appendString(ctx, b2, "map");
  }
  if (choice === 20) {
    appendString(ctx, b2, "mutates");
  }
  if (choice === 21) {
    appendString(ctx, b2, "extends");
  }
  if (choice === 22) {
    appendString(ctx, b2, "external");
  }
  if (choice === 23) {
    appendString(ctx, b2, "import");
  }
  if (choice === 24) {
    appendString(ctx, b2, "with");
  }
  if (choice === 25) {
    appendString(ctx, b2, "trait");
  }
  if (choice === 26) {
    appendString(ctx, b2, "initOf");
  }
  if (choice === 27) {
    appendString(ctx, b2, "override");
  }
  if (choice === 28) {
    appendString(ctx, b2, "abstract");
  }
  if (choice === 29) {
    appendString(ctx, b2, "virtual");
  }
  if (choice === 30) {
    appendString(ctx, b2, "inline");
  }
  if (choice === 31) {
    appendString(ctx, b2, "const");
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const space_plus_125: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth - 1);
  appendClass(ctx, b2, false, [" ", "\n", "\r", "\t", "\b", "\n", "\r", "\t", "\b", "\n", "\r", "\t", "\b"]);
  for (let i = 0; i < count; i++) {
    appendClass(ctx, b2, false, [" ", "\n", "\r", "\t", "\b", "\n", "\r", "\t", "\b", "\n", "\r", "\t", "\b"]);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const space_stringify_126: Rule = (ctx, b, field) => {
  space_plus_125(ctx, b);
};
export const space_lex_127: Rule = (ctx, b, field) => {
  space_stringify_126(ctx, b);
};
export const space_alt_128: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  const choice = randomInt(0, 1);
  if (choice === 0) {
    space_lex_127(ctx, b2);
  }
  if (choice === 1) {
    Comment(ctx, b2);
  }
  ctx.depth--;
  if (b2.length > 0) {
    b.push(...b2);
  }
};
export const multiLineComment_lookneg_129: Rule = (ctx, b, field) => {};
export const multiLineComment_seq_130: Rule = (ctx, b, field) => {
  ctx.depth++;
  const b2: Builder = [];
  multiLineComment_lookneg_129(ctx, b2);
  appendAny(ctx, b2);
  if (b2.length > 0) {
    b.push(...b2);
  }
  ctx.depth--;
};
export const multiLineComment_star_131: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    multiLineComment_seq_130(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const multiLineComment_stringify_132: Rule = (ctx, b, field) => {
  multiLineComment_star_131(ctx, b);
};
export const singleLineComment_star_133: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    appendClass(ctx, b2, true, ["\n", "\r", "\t", "\b", "\n", "\r", "\t", "\b"]);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const singleLineComment_stringify_134: Rule = (ctx, b, field) => {
  singleLineComment_star_133(ctx, b);
};
export const JustImports_star_135: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    Import(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const JustImports_star_136: Rule = (ctx, b, field) => {
  const b2: Builder = [];
  const maxWidth = ctx.maxWidth,
    count = randomInt(0, maxWidth);
  for (let i = 0; i < count; i++) {
    appendAny(ctx, b2);
  }
  if (b2.length > 0) {
    b.push(...b2);
  }
  return true;
};
export const inter_seq_137: (A: Rule, B: Rule) => Rule = (A, B) => {
  return (ctx, b, field) => {
    ctx.depth++;
    const b2: Builder = [];
    B(ctx, b2, "op");
    A(ctx, b2, "right");
    if (b2.length > 0) {
      b.push(...b2);
    }
    ctx.depth--;
  };
};
export const inter_star_138: (A: Rule, B: Rule) => Rule = (A, B) => {
  return (ctx, b, field) => {
    const b2: Builder = [];
    const maxWidth = ctx.maxWidth,
      count = randomInt(0, maxWidth);
    for (let i = 0; i < count; i++) {
      inter_seq_137(A, B)(ctx, b2);
    }
    if (b2.length > 0) {
      b.push(...b2);
    }
    return true;
  };
};